sonar.organization=the-dna-squad
sonar.projectKey=the-dna-squad_gctoolkit-IA-creation-video
sonar.projectName=chris-chedgey / gctoolkit / IA-creation-video

sonar.java.source=21
sonar.sourceEncoding=UTF-8
