sonar.host.url=https://sc-staging.io
sonar.organization=the-dna-squad
sonar.projectKey=the-dna-squad_gctoolkit-upstream-main
sonar.projectName=chris-chedgey / gctoolkit / upstream-main

sonar.java.source=21
sonar.sourceEncoding=UTF-8
